#!/usr/bin/env python3

from main import main
import sys
import os

# Add the script's directory to Python path to find our modules
script_dir = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, script_dir)


if __name__ == "__main__":
    main()

